from typing import Any, Tuple
import customtkinter as ctk
from tkinter import ttk
from typing import Literal, overload
import pywinstyles

from Logic import AppLogic, SystemNames, SaveObjectTypes, WarningWindowText, TrasactionStatuses, Fonts

class VisualFunctions(ctk.CTkBaseClass):
    '''
    A class to store wrappers of tkinter functions to be called by Logic:
    \nGENERAL
    \nupdate_window_data(): updates all specified window data outside of mainloop using .update()
    \nraise_panel(): raises a ctk.CTkFrame using tkraise()
    \nconfigure_widget(): alters the indicated parameter of a ctk widget using .configure()
    \nget_widget_width(): returns the current width of the widget in pixels using .winfo_width()
    \nget_widget_focus(): returns the widget that currently has focus using focus_get()
    \nset_widget_focus(): sets input focus to the passed widget using focus_set()
    \ndestroy_widget(): destroys the passed widget using .destroy()
    \nset_int_var(): inputs a new value into a ctk intvar using .set()
    \nset_str_var(): inputs a new string value into a ctk string var using .set()
    \nget_widget_attribute(): returns the attribute value for indicated widget using .cget()
    \nextract_int_var(): extracts a int from a ctk int var using .get()
    \nextract_str_var(): extracts a string from a ctk string var using .get()
    \nset_grab_to_widget(): this directs all events to the indicated widget (preventing interaction with others) using .grab_set()
    \nHIERARCHY/TREEVIEW
    \ninsert_into_hierarchy(): inserts text and values into a ttk Treeview widget using .insert()
    \ndelete_hierachy_item(): deletes a treeview item and all its children using .delete()
    \nget_hierarchy_item(): will either query or modify a treeview item using .item()
    \nget_hierarchy_parent_item(): will return ID of the parent of a treeview item using .parent()
    \nget_hierarchy_content(): returns either a string or list of text or values for a treeview item using .get()
    \nget_or_set_hierarchy_focus(): called by <<TreeviewSelect>> event, either sets focus to specified item, or returns current focus item using ttk's .focus()
    \nget_hierarchy_row(): returns string ID of treeview row at Y position, using identify_row()
    \nget_hierarchy_column(): returns string ID of treeview column at X position, using identify_column()
    \nconfigure_hierarchy_values(): allows configuration of the tags element of a treeview item using tag_configure()
    \nconfigure_hierarchy_options():  sets options for treeview using .configure()
    \ndraw_hierarchy_bbox(): will return the location and dimensions of a bounding box for a selected cell in a treeview using .bbox()
    \nset_hierarchy_column_options(): allows setting of column options in a treeview (no querying) using .column()
    \nset_hierarchy_heading_text(): allows setting of the heading text for a column using .heading()
    \nid_hierarchy_row(): returns the id of the item at position y (generated by event) using .identify_row()
    \nid_hierarchy_column(): returns the column identifier (in form str '#0') at position x (generated by event) using .identify_column()
    \nTEXTBOX
    \ntextbox_insert(): inserts text into text box using .insert()
    \ntextbox_delete(): deletes text from a text box using .delete()
    \ntextbox_get(): returns the text from a text box using .get()
    \ntextbox_markset_insert():  places a mark at specficied index of a textbox, in this case limited to an 'insert' type, using .mark_set()
    \nENTRYBOX
    \nentrybox_delete(): deletes text from an entry box using .delete()
    \nget_entrybox_content(): returns the content of specified entry box, using .get()
    \nCHECKBOX
    \ncheckbox_select(): sets the variable linked to a checkbox to the checkbox's value using .select()
    \ncheckbox_deselect(): unsets the variable linked to a checkbox to the checkbox's value using .deselect()
    \nget_checkbox_status(): returns the current status of a checkbox as 0 for unchecked, 1 for checked using .get()
    \nget_checkbox_attribute(): returns the value of a checkbox attribute, passed as string using .cget()
    \nTABVIEW
    \nset_active_tab(): set tab with provided name to be visible using .set()
    \nget_active_tab(): returns the name of the currently visible tab using .get()
    \nget_tab_index(): returns the index of the tab with the provided name using .index()
    \nBUTTON
    \ninvoke_button(): calls the command function/method attached to a button using .invoke()
    \nDROPDOWN MENU (CALLED COMBO BOX IN CTK)
    \nconfigure_dropdown(): takes and alters optional args for values, and variable in addtion to standard ctk widget properties using, .configure()
    '''
    def __init__(self, master):
        super().__init__(master)

    #GENERAL
    def update_window_data(self, window: ctk.CTk):
        '''forces an update of all pending window characteristics prior to mainloop'''
        window.update()

    def raise_panel(self, panel: ctk.CTkFrame):
        '''employ function tkraise to raise the indicated ctk frame'''
        panel.tkraise()

    def configure_widget(self, 
                         widget: ctk.CTkBaseClass, 
                         new_text: str | None = None, 
                         new_text_color: str | None = None, 
                         new_state: Literal['normal'] | Literal['disabled'] | None = None, 
                         new_font: Tuple | None = None):
        '''employ .configure to alter ctk widgets'''      
        if new_text != None: #apply new text, if passed
            widget.configure(text=new_text)
        if new_text_color != None: #apply new text color, if passed
            widget.configure(text_color=new_text_color)
        if new_state != None: #set new state, if passed
            widget.configure(state=new_state)
        if new_font != None:
            widget.configure(font=new_font)

    def get_widget_width(self, widget: ctk.CTk):
        return widget.winfo_width()

    def get_widget_focus(self, widget: ctk.CTk):
        widget.focus_get()

    def set_widget_focus(self, widget: ctk.CTk | Any):
        '''Warning: will throw exception if non-CTK object passed'''
        widget.focus_set()

    def destroy_widget(self, widget: ctk.CTk | Any):
        '''will destroy a CTk widget, Warning: will throw exception of non-CTk object is passed'''
        widget.destroy()

    def set_int_var(self, int_var: ctk.IntVar, new_value: int):
        int_var.set(new_value)

    def set_string_var(self, str_var: ctk.StringVar, new_value: str):
        str_var.set(new_value)

    def extract_int_var(self, int_var: ctk.IntVar) -> int:
        '''extracts list[int] from a tkinter Intvar'''
        extracted_int: int = int_var.get()
        return extracted_int
    
    def extract_str_var(self, str_var: ctk.StringVar) -> str:
        extracted_string: str = str_var.get()
        return extracted_string
    
    def get_widget_attribute(self, widget: ctk.CTk | Any, attribute: str):
        return widget.cget(attribute_name=attribute)
    
    def set_grab_to_widget(self, widget: ctk.CTk | Any):
        '''sets events to this widget, Warning: will throw exception if non-CTK object passed'''
        widget.grab_set()

    def widget_at_xy(self, parent: ctk.CTk | Any, x: int, y: int) -> Any | None:
        '''This returns the widget at coordinates (x,y),
        \nparent = reference to parent CTK widget (frame,window)
        \nNOTE: displayof not implemented'''
        return parent.winfo_containing(rootX=x, rootY=y)

    #TREEVIEW
    @overload
    def insert_into_hierarchy(self, hierarchy_name: ttk.Treeview, parent_item, index_location: int | Literal['end'], text_to_insert: str="", row_values: list | tuple=[], tags: tuple[str, ...] = ("",), display_open: bool=True) -> str: ...
    @overload
    def insert_into_hierarchy(self, hierarchy_name: ttk.Treeview, parent_item, index_location: int | Literal['end'], text_to_insert: str="", row_values: list | tuple=[], tags: None = None, display_open: bool=True) -> str: ...
    def insert_into_hierarchy(self, hierarchy_name: ttk.Treeview, parent_item, index_location: int | Literal['end'], text_to_insert: str="", row_values: list | tuple=[], tags: tuple[str, ...] | None = None, display_open: bool=True) -> str:
        if tags == None: #tag not passed, insert without
            hierarchy_object_id = hierarchy_name.insert(parent=parent_item, index=index_location, text=text_to_insert, values=row_values, open=display_open)
        else: #tags passed, insert with
            hierarchy_object_id = hierarchy_name.insert(parent=parent_item, index=index_location, text=text_to_insert, values=row_values, tags=tags, open=display_open)
        return hierarchy_object_id
        
    def delete_hierarchy_item(self, hierarchy_name: ttk.Treeview, hierarchy_item: str):
        hierarchy_name.delete(hierarchy_item)

    @overload
    def get_hierarchy_item(self, hierarchy_name: ttk.Treeview, item_name: str | int, new_text: str = "", new_values: list | None=None, new_tags: list[str] | tuple[str] | None=None,  display_open: bool=False): ...
    @overload
    def get_hierarchy_item(self, hierarchy_name: ttk.Treeview, item_name: str | int, new_text: str | None=None, new_values: list=[], new_tags: list[str] | tuple[str] | None=None,  display_open: bool=False): ...
    @overload
    def get_hierarchy_item(self, hierarchy_name: ttk.Treeview, item_name: str | int, new_text: str | None=None, new_values: list | tuple | None=None, new_tags: list[str] | tuple[str] = [""],  display_open: bool=False): ...
    def get_hierarchy_item(self, hierarchy_name: ttk.Treeview, item_name: str | int, new_text: str | None=None, new_values: list | tuple | None=None, new_tags: list[str] | tuple[str] | None=None,  display_open: bool=False):
        '''NOTE: returns a treeview item dict, and allows editing of existing item's content with 'new_values', 'new_text', and 'new_tags' args'''
        hierarchy = hierarchy_name.item(item=item_name, open=display_open) #no data passed, simply return the hierarchy item
        if new_text != None: #text was passed
            hierarchy = hierarchy_name.item(item=item_name, text=new_text, open=display_open)
        if new_values != None: #values were passed
            hierarchy = hierarchy_name.item(item=item_name, values=new_values, open=display_open)
        if new_tags != None: #tags were passed
            hierarchy = hierarchy_name.item(item=item_name, tags=new_tags, open=display_open)
        return hierarchy
        
    def get_hierarchy_item_parent(self, hierarchy_name: ttk.Treeview, item_name: str | int) -> str:
        '''NOTE: arg: dict defaults to False.  If True, returns a treeview item dict.  If False, returns a treeview Item ID as a str'''
        return hierarchy_name.parent(item=item_name)
    
    def get_hierarchy_item_children(self, hierarchy_name: ttk.Treeview, item_name: str | int | None = None) -> tuple[str, ...]:
        return hierarchy_name.get_children(item=item_name)
    
    def get_hierarchy_item_index(self, hierarchy_name: ttk.Treeview, item_name: str | int) -> int:
        return hierarchy_name.index(item=item_name)
    
    def move_hierarchy_item(self, hierarchy_name: ttk.Treeview, item_name: str | int, new_index: int | Literal['end']):
        hierarchy_name.move(item=item_name, parent=self.get_hierarchy_item_parent(hierarchy_name, item_name), index=new_index)
    
    @overload
    def get_hierarchy_content(self, hierarchy_name: ttk.Treeview, item_name: str | int, content: Literal["text"]) -> str: ...
    @overload
    def get_hierarchy_content(self, hierarchy_name: ttk.Treeview, item_name: str | int, content: Literal["values"]) -> list[Any]: ...
    @overload
    def get_hierarchy_content(self, hierarchy_name: ttk.Treeview, item_name: str | int, content: Literal["tags"]) -> list[str]: ...

    def get_hierarchy_content(self, hierarchy_name: ttk.Treeview, item_name: str | int, content: Literal['text'] | Literal['values'] | Literal['tags']) -> str | list[Any] | list[str]:
        hierarchy_name.item
        if content == "text":
            hierarchy_content = hierarchy_name.item(item=item_name).get("text")
        elif content == 'values':
            hierarchy_content = hierarchy_name.item(item=item_name).get("values")
        elif content == 'tags':
            hierarchy_content = hierarchy_name.item(item=item_name).get("tags")
        else:
            hierarchy_content = ""
        return hierarchy_content    
    
    def get_hierarchy_focus(self, hierarchy_name: ttk.Treeview):
        '''Returns treeview item ID: str of current item with focus'''
        return hierarchy_name.focus()
    
    def get_hierarchy_row(self, hierarchy_name: ttk.Treeview, y_pos: int) -> str:
        '''use y_pos=event.y when triggered by event'''
        return hierarchy_name.identify_row(y=y_pos)
    
    def get_hierarchy_column(self, hierarchy_name: ttk.Treeview, x_pos) -> str:
        '''use x_pos=event.x when triggered by event'''
        return hierarchy_name.identify_column(x=x_pos)
        
    def set_hierarchy_focus(self, hierarchy_name: ttk.Treeview, item_name: None | str | int ):
        '''takes a treeview item ID, and sets focus to it'''
        hierarchy_name.focus(item=item_name)
    
    def set_hierarchy_single_selection(self, hierarchy_name: ttk.Treeview, item: str| int):
        hierarchy_name.selection_set(item)

    def configure_hierarchy_values(self, hierarchy_name: ttk.Treeview, font_name: str, font_family: str = "Calibri", size: int = 12, font_modifier: str = "", text_color: str = ""):
        '''configures a font that can be applied to the inserted values for the indicated treeview
         \napplied using tags= option in .insert (.insert_into_hierarchy) or .item(.get_hierarchy_item) methods (uses tag_configure)
         \n to apply: hierarchy_name.insert("", 'end', values=(text to be entered), tags = (font name (as a string),))
        \nfont modifiers: bold, italic, underline, overstrike'''
        hierarchy_name.tag_configure(font_name, font=(font_family, size, font_modifier), foreground=text_color)

    def configure_hierarchy_options(self, hierarchy_name: ttk.Treeview, columns: str | list[str] | list[int]):
        '''set widget options for a ttk.Treeview
        \nincluded options: columns (more can be addded as needed)'''
        hierarchy_name.configure(columns=columns)

    def draw_hierarchy_bbox(self, hierarchy_name: ttk.Treeview, item_name: str, col: str | int) -> tuple[int, int, int, int] | Literal['']:
        '''returns location and dimensions of a bounding box, for a treeview item, and specificly for the seleted cell if col is specified
        \nreturns x, y, width, height'''
        return hierarchy_name.bbox(item=item_name, column=col)
    
    def set_hierarchy_column_options(self, hierarchy_name: ttk.Treeview, column: str | int, width: int | None = None, minwidth: int | None = None, stretch: bool | None = None) -> None:
        '''specific implementation for setting column options (no querying/getting)
        \n/includes only 3 optional args: width, minwidth, stretch'''
        if width != None:
            hierarchy_name.column(column, width=width)
        if minwidth != None:
            hierarchy_name.column(column, minwidth=minwidth)
        if stretch != None:
            hierarchy_name.column(column, stretch=stretch)
    
    def set_hierarchy_heading_text(self, hierarchy_name: ttk.Treeview, column: str | int, text: str):
        hierarchy_name.heading(column, text=text)

    def id_hierarchy_row(self, hierarchy_name: ttk.Treeview, y: int) -> str:
        return hierarchy_name.identify_row(y)
    
    def id_hierarchy_column(self, hierarchy_name: ttk.Treeview, x: int) -> str:
        return hierarchy_name.identify_column(x)
        
    #TEXTBOX
    def textbox_insert(self, textbox: ctk.CTkTextbox, index: str, text: str, tags: None | str = None):
        '''insert text into specified textbox BEFORE characters at index, add tags as optional arg'''
        textbox.insert(index=index, text=text, tags=tags)

    def textbox_delete(self, textbox: ctk.CTkTextbox, index1: str, index2: str | None):
        '''delete chars between index1(inclusive) and index 2(not inclusive). Can pass string literal "end" for index 2'''
        textbox.delete(index1=index1, index2=index2)

    def textbox_get(self, textbox: ctk.CTkTextbox, index1: str, index2: str | None) -> str:
        '''return chars between index1(inclusive) and index 2(not inclusive). Can pass string literal "end-1c" for index 2'''
        return textbox.get(index1=index1, index2=index2)

    def textbox_markset_insert(self, textbox: ctk.CTkTextbox, index: str):
        '''add an 'insert' mark at index in specified textbox'''
        textbox.mark_set(mark="insert", index=index)

    #ENTRYBOX
    def entrybox_delete(self, entrybox: ctk.CTkEntry, index1: str, index2: str | None):
        '''delete chars between index1(inclusive) and index 2(not inclusive). Can pass string literal "end" for index 2'''
        entrybox.delete(first_index=index1, last_index=index2)

    def get_entrybox_content(self, entrybox: ctk.CTkEntry) -> str:
        return entrybox.get()
    
    def set_entrybox_cursor(self, entrybox: ctk.CTkEntry, index: int | Literal['end']):
        entrybox.icursor(index)
    
    def set_entrybox_selection_range(self, entrybox: ctk.CTkEntry, index_start: int, index_end: int | Literal['end']):
        entrybox.select_range(index_start, index_end)

    #CHECKBOX
    def checkbox_select(self, checkbox: ctk.CTkCheckBox) -> None:
        checkbox.select()

    def checkbox_deselect(self, checkbox: ctk.CTkCheckBox) -> None:
        checkbox.deselect()

    def get_checkbox_status(self, checkbox: ctk.CTkCheckBox) -> str | int:
        return checkbox.get()
    
    def get_checkbox_attribute(self, checkbox: ctk.CTkCheckBox, attribute: str):
        return checkbox.cget(attribute)
    
    #TABIVEW
    def set_active_tab(self, tabview: ctk.CTkTabview, tab_name: str):
        tabview.set(tab_name)

    def get_active_tab(self, tabview: ctk.CTkTabview):
        return tabview.get()
    
    def get_tab_index(self, tabview: ctk.CTkTabview, tab_name: str):
        return tabview.index(tab_name)
    
    #BUTTON
    def invoke_button(self, button: ctk.CTkButton):
        button.invoke()

    #DROPDOWN MENU
    def configure_dropdown(self, dropdown: ctk.CTkComboBox, values: list | None = None, variable: ctk.StringVar | ctk.IntVar | None = None, **kwargs):
        dropdown.configure(values=values, variable=variable, **kwargs)
    
    #general: .focus_set NOTE .focus is an older but compatible version of this, could update all general tkinter widget .focus function calls with focus_set()

class VisualThemes(ctk.CTkBaseClass):
    '''Contains methods to set visual themes for program widgets
    \nThemes included:
    \nHierarchical Menu (Treeview)
    \nData Table (currently Treeview)
    '''
    def __init__(self, master):
        super().__init__(master)
    
    def apply_style_hierarchical_menu(self, widget: ctk.CTkFrame):
        self.bg_color = widget._apply_appearance_mode(ctk.ThemeManager.theme["CTkFrame"]["fg_color"])
        self.selected_color = widget._apply_appearance_mode(ctk.ThemeManager.theme["CTkButton"]["fg_color"])
        self.text_color = widget._apply_appearance_mode(ctk.ThemeManager.theme["CTkLabel"]["text_color"])

        self.template_editor_style = ttk.Style()
        self.template_editor_style.theme_use('default')
        self.template_editor_style.configure("Treeview", fieldbackground=self.bg_color, background=self.bg_color, foreground=self.text_color, font=('calibri', 15), borderwidth=0, rowheight=23)
        self.template_editor_style.map("Treeview", background=[("selected", self.bg_color)], foreground=[("selected", self.selected_color)]) 

    def apply_style_table(self, widget: ctk.CTkFrame):
        self.bg_color_table = widget._apply_appearance_mode(ctk.ThemeManager.theme["CTkFrame"]["fg_color"])
        self.selected_color_table = widget._apply_appearance_mode(ctk.ThemeManager.theme["CTkButton"]["fg_color"])
        self.text_color_table = widget._apply_appearance_mode(ctk.ThemeManager.theme["CTkLabel"]["text_color"])

        self.template_table_style = ttk.Style(self)
        self.template_table_style.theme_use('default')
        self.template_table_style.configure("Treeview", fieldbackground=self.bg_color_table, background=self.bg_color_table, foreground=self.text_color_table, font=('calibri', 15), borderwidth=0, rowheight=28)
        self.template_table_style.configure("Treeview.Heading", borderwidth=1, relief="ridge", background=self.bg_color_table, foreground=self.text_color_table, font=('calibri', 15))
        self.template_table_style.configure("Treeview.Heading", font=("Calibri", 14))
        self.template_table_style.map("Treeview", background=[("selected", "#303030")], foreground=[("selected", self.selected_color_table)]) #unlike hierarchy, selected cell should be lighter than ctkframe default color

class NavigationPanel(ctk.CTkFrame):
    def __init__(self, master: Any, app_logic: AppLogic):
        super().__init__(master)
        self.configure(bg_color="#3b3b3b", corner_radius = 0)
        self.grid_columnconfigure((0,1,2,3), weight=1)
        self.grid_rowconfigure(0, weight=1)

        #variables
        self.app_logic = app_logic

        #widgets    
        self.button_continue = ctk.CTkButton(self, text="Continue", fg_color="#00aaff", font=('calibri', 35), command=app_logic.nav_panel_continue_button)
        self.button_back = ctk.CTkButton(self, text="Back", fg_color="#00aaff", font=('calibri', 35), command=app_logic.nav_panel_back_button)
        
        self.delete_radiobutton_button = ctk.CTkButton(self, text="Delete", fg_color="#00aaff", font=('calibri', 35), state="disabled", command=lambda: self.app_logic.delete_radiobutton_selection()) 
        self.confirm_radiobutton_button = ctk.CTkButton(self, text="Confirm Deletions", fg_color="#00aaff", font=('calibri', 35), state="disabled", command=lambda: self.app_logic.confirm_radiobutton_deletions()) 
        
        self.add_new_transaction_button = ctk.CTkButton(self, text="Add New Transaction", fg_color="#00aaff", font=('calibri', 35), state="disabled", command=lambda: self.app_logic.get_selected_cell_info(add_new_from_navpanel=1))
        self.edit_transactions_button = ctk.CTkButton(self, text="Edit Transactions", fg_color="#00aaff", font=('calibri', 35), state="disabled", command=lambda: self.app_logic.get_selected_cell_info(add_new_from_navpanel=0))
        #layout
        self.button_continue.grid(row=0, column=3, sticky="ne", pady=10, padx=10) 
        self.button_back.grid(row=0, column=0, sticky="nw", pady=10, padx=10)
    
    #methods:
    def enable_radiobutton_buttons(self):
        self.delete_radiobutton_button.grid(row=0, column=1, sticky="new", pady=10, padx=10)
        self.confirm_radiobutton_button.grid(row=0, column=2, sticky="new", pady=10, padx=10)

    def disable_radiobutton_buttons(self):        
        self.delete_radiobutton_button.grid_forget()
        self.confirm_radiobutton_button.grid_forget()

    def set_radiobutton_buttons_to_inactive(self):
        self.delete_radiobutton_button.configure(state='disabled')
        self.confirm_radiobutton_button.configure(state='disabled')

    def enable_manager_buttons(self):
        self.add_new_transaction_button.grid(row=0, column=1, sticky="new", pady=10, padx=10)
        self.edit_transactions_button.grid(row=0, column=2, sticky="new", pady=10, padx=10)

    def disable_manager_buttons(self):
        self.add_new_transaction_button.grid_forget()
        self.edit_transactions_button.grid_forget()

class MainMenu(ctk.CTkFrame):
    def __init__(self, master: Any, create_new_system: SystemNames, manage_budget_system: SystemNames, app_logic: AppLogic):
        super().__init__(master)

        #Panel Chars
        self.grid_columnconfigure((0,2), weight=(1), uniform='a')
        self.grid_columnconfigure((1), weight=(4), uniform='a')
        self.grid_rowconfigure((0), weight=2)
        self.grid_rowconfigure((1,2,3), weight=1)
        self.grid_rowconfigure((4), weight=0)

        #Widgets
        self.main_menu_label = ctk.CTkLabel(self, text="Manage Your Money", text_color="#00aaff", font=('calibri', 65)) 
        #NOTE: ensure that the string passed into system_selction matches str passed into corresponding instance
        self.create_new_button = ctk.CTkButton(self, text="Create a New Budget", fg_color="#00aaff", font=('calibri', 40), command=lambda: app_logic.system_selection(create_new_system))
        self.open_existing_button = ctk.CTkButton(self, text="Manage an Existing Budget", fg_color="#00aaff", font=('calibri', 40), command = lambda: app_logic.system_selection(manage_budget_system))
        self.options_button = ctk.CTkButton(self, text="Options", fg_color="#00aaff", font=('calibri', 40))

        self.version_note = ctk.CTkLabel(self, text="Version 0.3.1", text_color="#686868")

        #layout
        self.main_menu_label.grid(row=0, column=1, columnspan=1, sticky='ew')

        self.create_new_button.grid(row=1, column=1, padx=50, pady=10, sticky='ns')
        self.open_existing_button.grid(row=2, column=1, padx=50, pady=10, sticky='ns')
        self.options_button.grid(row=3, column=1, padx=10, pady=10, ipadx=110, sticky='ns') 

        self.version_note.grid(row=4, column=2)
        
class RadioButtonMenu(ctk.CTkFrame):
    def __init__(self, parent, system_name: SystemNames, app_logic: AppLogic, menu_title: str):
        super().__init__(master=parent)
        self.configure(corner_radius = 0)
        self.grid_columnconfigure(0, weight=10)
        self.grid_columnconfigure(1, weight=1)
        self.grid_rowconfigure(0, weight=2)
        self.grid_rowconfigure(1, weight=1)
        self.grid_rowconfigure(2, weight=50)

        #variables for visuals
        self.selected_object_name_widget_str = ctk.StringVar(value="")
        self.system_name = system_name
        self.app_logic = app_logic
        
        #this is needed for any page that has more than one instance
        if system_name == SystemNames.create_new_system:
            self.page_func = app_logic.display_template_list
        elif system_name == SystemNames.manage_budget_system:
            self.page_func = app_logic.display_budget_files

        #widgets
        self.menu_label = ctk.CTkLabel(self, text=menu_title, text_color="#00aaff", font=('calibri', 55))

        self.scrolling_list = ctk.CTkScrollableFrame(self)
        
        #layout
        self.menu_label.grid(row=0, column=0, sticky='ew', columnspan=2)
    
        self.scrolling_list.grid(row=2, column=0, sticky='nsew', padx=80, columnspan=2)
        self.scrolling_list.grid_columnconfigure(0, weight=1)
        self.scrolling_list.grid_rowconfigure(0, weight=1)

        app_logic.add_to_nav_map(system_name.value, self, self.page_func)
            
    #methods
    def create_radiobuttons(self, file_or_template_names: list[str]): #create radiobuttons from file/template list
        self.radiobutton_list: list[ctk.CTkRadioButton] = []
        for i, file_template in enumerate(file_or_template_names):
            self.radiobutton = ctk.CTkRadioButton(self.scrolling_list, text=file_template, font=("Calibri", 15), value=file_template, variable=self.selected_object_name_widget_str, command=lambda: self.app_logic.activate_delete_radiobutton_button())
            self.radiobutton.grid(row=0+i, column=0, pady=5, sticky="w")
            self.radiobutton_list.append(self.radiobutton)

    def destroy_radiobuttons(self):
        try:
            for rb in self.radiobutton_list:
                rb.destroy()
        except AttributeError:
            pass #radiobuttons not found, nothing to delete
    
    def clear_selection(self): #upon system selection (entering from main menu), clear any selected radiobuttons and string var
        self.selected_object_name_widget_str.set(value="")
        for button in self.radiobutton_list:
            button.deselect()

class EditBudgetTemplate(ctk.CTkFrame):
    def __init__(self, parent, system_name: SystemNames, app_logic: AppLogic, visual_themes: VisualThemes):
        super().__init__(master=parent)
        self.configure(corner_radius = 0)

        #Variables
        self.monthly_annual = ctk.IntVar()
        self.app_logic = app_logic
        self.system_name = system_name
        self.context_menu_text_box_focus = 0 #keep track of text box focus for context menu
        self.page_func = app_logic.display_template_and_title

        #Widgets
        #page labels
        self.template_editor_title = ctk.CTkLabel(self, text="Edit Budget Template", text_color="#00aaff", font=('calibri', 45))
        self.template_title_label = ctk.CTkLabel(self, text_color="#00aaff", font=('calibri', 35))

        #template editor frame
        self.budget_template_frame = ctk.CTkFrame(self)
        self.template_editor = ttk.Treeview(self.budget_template_frame, show='tree', selectmode='browse')
        self.budget_frame_scrollbar = ctk.CTkScrollbar(self.budget_template_frame, command=self.template_editor.yview)

        #contextual menu 
        #intro message
        self.context_intro_message = ctk.CTkFrame(self)
        self.intro_message_label = ctk.CTkLabel(self.context_intro_message, text="To Edit Budget,\n Select a Component\n from the Menu")

        #income/expense selected
        self.context_income_expense = ctk.CTkFrame(self)
        self.income_expense_label = ctk.CTkLabel(self.context_income_expense, text_color='#ffffff', font=('calibri', 15))
        self.category_text_box = ctk.CTkTextbox(self.context_income_expense, height=100) #do we want word based text wrapping? default is character

        self.add_category_button = ctk.CTkButton(self.context_income_expense, text="Add New Category", fg_color="#00aaff", font=('calibri', 18), command=lambda widget=self.category_text_box : app_logic.add_textbox_content_to_template_editor(widget))

        #category selected
        self.context_category = ctk.CTkFrame(self)
        self.category_label = ctk.CTkLabel(self.context_category, text="Category Selected", text_color='#ffffff')
        
        self.category_text_box_in_category_menu = ctk.CTkTextbox(self.context_category, height=50)
        self.rename_category_button = ctk.CTkButton(self.context_category, text="Rename", fg_color="#00aaff", font=('calibri', 18), command=lambda widget=self.category_text_box_in_category_menu : app_logic.rename_hierachy_item(widget))
        self.moveup_category_button = ctk.CTkButton(self.context_category, text="Move Up", fg_color="#00aaff", font=('calibri', 18), command=app_logic.move_hierarchy_item_up)
        self.movedown_category_button = ctk.CTkButton(self.context_category, text="Move Down", fg_color="#00aaff", font=('calibri', 18), command=app_logic.move_hierarchy_item_down)
        self.delete_category_button = ctk.CTkButton(self.context_category, text="Delete Category", fg_color="#00aaff", font=('calibri', 18), command=app_logic.delete_selected_hierarchy_item)

        self.subcategory_text_box_in_category_menu = ctk.CTkTextbox(self.context_category, height=50)
        self.add_subcategory_button = ctk.CTkButton(self.context_category, text="Add New Sub-Category", fg_color="#00aaff", font=('calibri', 16), command=lambda widget=self.subcategory_text_box_in_category_menu : app_logic.add_textbox_content_to_template_editor(widget))

        #sub-category selected
        self.context_subcategory = ctk.CTkFrame(self)
        self.subcategory_label = ctk.CTkLabel(self.context_subcategory, text="Sub-category Selected", text_color='#ffffff')
        
        self.subcategory_textbox = ctk.CTkTextbox(self.context_subcategory, height=50)
        self.rename_subcategory_button = ctk.CTkButton(self.context_subcategory, text="Rename", fg_color="#00aaff", font=('calibri', 18), command=lambda widget=self.subcategory_textbox : app_logic.rename_hierachy_item(widget))
        self.moveup_subcategory_button = ctk.CTkButton(self.context_subcategory, text="Move Up", fg_color="#00aaff", font=('calibri', 18), command=app_logic.move_hierarchy_item_up)
        self.movedown_subcategory_button = ctk.CTkButton(self.context_subcategory, text="Move Down", fg_color="#00aaff", font=('calibri', 18), command=app_logic.move_hierarchy_item_down)
        self.delete_subcategory_button = ctk.CTkButton(self.context_subcategory, text="Delete Sub-category", fg_color="#00aaff", font=('calibri', 18), command=app_logic.delete_selected_hierarchy_item)

        self.subcategory_annual_checkbox= ctk.CTkCheckBox(self.context_subcategory, text="Annual", fg_color="#00aaff", font=('calibri', 18), onvalue=2, offvalue=1, variable=self.monthly_annual, command=app_logic.set_monthly_annual_checkbox_status)

        #save button
        self.save_button_frame = ctk.CTkFrame(self)
        self.save_template_button = ctk.CTkButton(self.save_button_frame, text="Save Template", fg_color="#00aaff", font=('calibri', 18), command=lambda: self.raise_save_template_window(app_logic))

        #Layout
        #page labels
        self.template_editor_title.place(relx=0.5, rely=0, anchor='n')
        self.template_title_label.place(relx=0.5, rely=0.1, anchor='n')

        #main frame: the template
        self.budget_template_frame.place(relx=0.08, rely=0.2, relwidth=0.65, relheight=0.80, anchor='nw')
        self.budget_frame_scrollbar.pack(side='right', fill='y')
        self.template_editor.pack(side='left', expand=True, fill='both', padx=(10,0), pady=10)
        self.template_editor.configure(yscrollcommand=self.budget_frame_scrollbar.set)
        #contextual menu
        #intro message
        self.context_intro_message.place(relx=0.74, rely=0.2, relwidth=0.18, relheight=0.70, anchor='nw')
        self.intro_message_label.pack()
        #income/expense
        self.context_income_expense.place(relx=0.74, rely=0.2, relwidth=0.18, relheight=0.70, anchor='nw')
        self.income_expense_label.pack()
        self.category_text_box.pack(padx=10, pady=5)
        self.add_category_button.pack(padx=10, pady=5)
        #category selected
        self.context_category.place(relx=0.74, rely=0.2, relwidth=0.18, relheight=0.70, anchor='nw')
        self.category_label.pack()
        self.category_text_box_in_category_menu.pack(padx=10, pady=5)
        self.rename_category_button.pack(padx=10, pady=5)
        self.moveup_category_button.pack(padx=10, pady=5)
        self.movedown_category_button.pack(padx=10, pady=5)
        self.delete_category_button.pack(padx=10, pady=5)
        self.subcategory_text_box_in_category_menu.pack(padx=10, pady=5)
        self.add_subcategory_button.pack(padx=10, pady=5)
        #sub-category selected
        self.context_subcategory.place(relx=0.74, rely=0.2, relwidth=0.18, relheight=0.70, anchor='nw')
        self.subcategory_label.pack()
        self.subcategory_textbox.pack(padx=10, pady=5)
        self.rename_subcategory_button.pack(padx=10, pady=5)
        self.moveup_subcategory_button.pack(padx=10, pady=5)
        self.movedown_subcategory_button.pack(padx=10, pady=5)
        self.delete_subcategory_button.pack(padx=10, pady=5)
        self.subcategory_annual_checkbox.pack(padx=10, pady=5)
        #save button
        self.save_button_frame.place(relx=0.74, rely=0.92, relwidth=0.18, relheight=0.08, anchor='nw')
        self.save_template_button.pack(padx=5, pady=5, expand=True, fill='both')

        #Events
        #raise context menu on select of template component
        self.template_editor.bind("<<TreeviewSelect>>", app_logic.raise_context_menu)

        #income/expense focus
        self.category_text_box.bind("<FocusIn>", lambda event: self.add_context_menu_textbox_focus(event, self.category_text_box))
        self.category_text_box.bind("<FocusOut>", lambda event: self.remove_context_menu_textbox_focus(event, self.category_text_box))

        # #category focus
        self.category_text_box_in_category_menu.bind("<FocusIn>", lambda event: self.add_context_menu_textbox_focus(event, self.category_text_box_in_category_menu))
        self.category_text_box_in_category_menu.bind("<FocusOut>", lambda event: self.remove_context_menu_textbox_focus(event, self.category_text_box_in_category_menu))

        self.subcategory_text_box_in_category_menu.bind("<FocusIn>", lambda event: self.add_context_menu_textbox_focus(event, self.subcategory_text_box_in_category_menu))
        self.subcategory_text_box_in_category_menu.bind("<FocusOut>", lambda event: self.remove_context_menu_textbox_focus(event, self.subcategory_text_box_in_category_menu))

        #subcategory focus 
        self.subcategory_textbox.bind("<FocusIn>", lambda event: self.add_context_menu_textbox_focus(event, self.subcategory_textbox))
        self.subcategory_textbox.bind("<FocusOut>", lambda event: self.remove_context_menu_textbox_focus(event, self.subcategory_textbox))

        self.textbox_dict = {self.category_text_box : lambda event, widget=self.category_text_box : app_logic.add_textbox_content_to_template_editor(widget, event), 
                        self.category_text_box_in_category_menu : lambda event, widget=self.category_text_box_in_category_menu : app_logic.rename_hierachy_item(widget, event),
                        self.subcategory_text_box_in_category_menu : lambda event, widget=self.subcategory_text_box_in_category_menu : app_logic.add_textbox_content_to_template_editor(widget, event),
                        self.subcategory_textbox : lambda event, widget=self.subcategory_textbox : app_logic.rename_hierachy_item(widget, event)}
        
        app_logic.add_to_nav_map(system_name.value, self, self.page_func)
        visual_themes.apply_style_hierarchical_menu(self.budget_template_frame)

    #methods
    def add_context_menu_textbox_focus(self, event, widget: ctk.CTkTextbox):
        if self.context_menu_text_box_focus == 0:
            self.context_menu_text_box_focus = 1
            widget.bind("<Return>", self.textbox_dict.get(widget, Any))
    
    def remove_context_menu_textbox_focus(self, event, widget: ctk.CTkTextbox):
        if self.context_menu_text_box_focus == 1:
            self.context_menu_text_box_focus = 0
            widget.unbind("<Return>")

    def raise_save_template_window(self, app_logic: AppLogic):
        self.save_template_window = SaveNameWindow(self, SaveObjectTypes.template, app_logic, app_logic.selected_template_title)
        self.save_template_window.focus()
        self.save_template_window.grab_set()    

class EditBudget(ctk.CTkFrame):
    def __init__(self, parent, system_name: SystemNames, app_logic: AppLogic, visual_themes: VisualThemes):
        super().__init__(master=parent)
        self.configure(corner_radius = 0)
        self.grid_columnconfigure(0, weight=1)
        self.grid_rowconfigure(0, weight=1)    
        self.grid_rowconfigure(1, weight=50) 

        #variables
        self.app_logic = app_logic
        self.page_func = app_logic.display_budget_table
        self.entry_box_exists: bool = False

        #widgets
        self.enter_budget_amounts_label = ctk.CTkLabel(self, text="Enter Monthly and Annual Budget Amounts", text_color="#00aaff", font=('calibri', 35))
        
        self.budget_table_frame = ctk.CTkFrame(self)
        
        self.budget_displayed = 0 #indicator: budget is displayed in table NOTE this will likely be need in logic, not here
        self.budget_table = ttk.Treeview(self.budget_table_frame, columns=('category', 'annual', 'monthly'), show='headings')#, style="Treeview")
        self.budget_table.heading('category', text="Budget Category")
        self.budget_table.heading('annual', text="Annual Amount")
        self.budget_table.heading('monthly', text="Monthly Amount")
        self.budget_table.column('annual', anchor='center')
        self.budget_table.column('monthly', anchor='center')
        self.budget_table_scrollbar = ctk.CTkScrollbar(self.budget_table_frame, command=self.drag_scrollbar)

        #layout
        self.enter_budget_amounts_label.grid(row=0, column=0, sticky='new')

        self.budget_table_frame.grid(row=1, column=0, padx=80, sticky='nsew')
        self.budget_table_scrollbar.pack(side='right', fill='y')
        self.budget_table.pack(side='left', expand=True, fill='both', padx=(5,0), pady=5)
        self.budget_table.configure(yscrollcommand=self.budget_table_scrollbar.set)

        app_logic.add_to_nav_map(system_name.value, self, self.page_func)
        visual_themes.apply_style_table(self)

        #events
        self.budget_table.bind("<Double-1>", lambda event: self.app_logic.budget_table_double_click(event))
        self.budget_table.bind("<MouseWheel>", lambda event: self.treeview_scroll(event))

    #methods
    #create entry boxes on dbl click
    def draw_budget_entry_box(self):
        self.box_x_pos, self.box_y_pos, self.box_width, self.box_height = self.app_logic.set_entrybox_location()
        self.budget_entry = ctk.CTkEntry(self.budget_table, width=self.box_width, height=self.box_height)
        self.budget_entry.place(x=self.box_x_pos, y=self.box_y_pos)
        self.entry_box_exists = True
        self.budget_entry.focus()
        self.budget_entry.bind("<Return>", lambda event: self.app_logic.update_budget_table_entry(event, self.budget_entry))
        self.budget_entry.bind("<FocusOut>", lambda event: self.app_logic.update_budget_table_entry(event, self.budget_entry))

    def drag_scrollbar(self, *args): 
        self.budget_table.yview(*args)
        if self.entry_box_exists:
            try:
                self.box_x_pos, self.box_y_pos, self.box_width, self.box_height = self.app_logic.set_entrybox_location()
                self.budget_entry.place(x=self.box_x_pos, y=self.box_y_pos)
            except IndexError:
                self.budget_entry.place_forget() #selected cell out of view, unmap entry box
                
    def treeview_scroll(self, event): 
        '''reads current position of the top and bottom of the scrollbar, 
        \nthen if not at the top/bottom, adjusts the cell highlight by the cell height 
        \n(this is how much the treeview scrolls per mousewheel tick)'''       
        y_top, y_bottom = self.budget_table.yview()
        if self.entry_box_exists:       
            if event.delta < 0 and y_bottom < 1: #scrolling down and not at bottom, adjust y up 
                self.box_y_pos -= self.box_height   
                self.budget_entry.place(x=self.box_x_pos, y=self.box_y_pos)
            elif event.delta > 0 and y_top > 0: #scrolling up, adjust y down
                self.box_y_pos += self.box_height
                self.budget_entry.place(x=self.box_x_pos, y=self.box_y_pos)
        else: pass

    def raise_blank_cells_error(self):
        self.blank_cells_window = EditBudgetBlankCellsWindow(self, self.app_logic)

class EditBudgetBlankCellsWindow(ctk.CTkToplevel):
    def __init__(self, parent, app_logic: AppLogic):
        super().__init__(master=parent)
        
        #Panel chars
        self.title("Blank Budget Categories")
        self.geometry("750x500")
        self.minsize(750, 500)
        self.focus()
        self.grab_set()
        self.grid_columnconfigure((0,1), weight=1, uniform="a")
        self.grid_rowconfigure(0, weight=1)
        self.grid_rowconfigure(1, weight=50)
        self.grid_rowconfigure(2, weight=1)

        #widgets
        self.blank_cells_message = ctk.CTkLabel(self, text="Some of Your Budget Categories Have No Assigned Values.\nDo You Want to Proceed Anyway (They will be Given a Value of 0)?", text_color="#00aaff", font=('calibri', 18))

        self.blank_annual_scrolling_frame = ctk.CTkScrollableFrame(self)
        self.blank_annual_list_title = ctk.CTkLabel(self.blank_annual_scrolling_frame, text="Annual", font=("calibri", 20, "underline"))
        self.blank_annual_list = ctk.CTkLabel(self.blank_annual_scrolling_frame, text=app_logic.blank_annuals)

        self.blank_monthly_scrolling_frame = ctk.CTkScrollableFrame(self)
        self.blank_monthly_list_title = ctk.CTkLabel(self.blank_monthly_scrolling_frame, text="Monthly", font=("calibri", 20, "underline"))
        self.blank_monthly_list = ctk.CTkLabel(self.blank_monthly_scrolling_frame, text=app_logic.blank_monthlies)

        self.blank_cells_cancel = ctk.CTkButton(self, text="Cancel", fg_color="#00aaff", font=("calibri", 18), command=lambda: app_logic.return_to_budget_editor(self)) 
        self.blank_cells_confirm = ctk.CTkButton(self, text="Confirm", fg_color="#00aaff", font=("calibri", 18), command=lambda: app_logic.fill_empty_cells_with_0())

        #layout
        self.blank_cells_message.grid(row=0, column=0, columnspan=2, sticky="new")

        self.blank_annual_scrolling_frame.grid(row=1, column=0, padx=(10, 5), pady=(10, 0), sticky="nsew")
        self.blank_monthly_scrolling_frame.grid(row=1, column=1, padx=(0, 10), pady=(10, 0), sticky="nsew")

        self.blank_annual_list_title.pack()
        self.blank_annual_list.pack()
        self.blank_monthly_list_title.pack()
        self.blank_monthly_list.pack()

        self.blank_cells_cancel.grid(row=2, pady=10, column=0)
        self.blank_cells_confirm.grid(row=2, pady=10, column=1)

class AccountSelection(ctk.CTkFrame):
    def __init__(self, parent, system_name: SystemNames, app_logic: AppLogic):
        super().__init__(master=parent)

        #panel chars
        self.configure(corner_radius = 0)
        self.grid_columnconfigure((0,1), weight=1, uniform='a')
        self.grid_rowconfigure((0,1,2,3,4), weight=1)
        self.grid_rowconfigure(5, weight=50)
        
        #variables
        self.system_name = system_name
        self.default_account_name_list = ["All Accounts", "Chequing", "Savings", "Money Market Account", "Credit Card", "Line of Credit"]
        self.page_func = app_logic.check_budget_table

        #widgets
        account_selection_message_0 = ctk.CTkLabel(self, text="One Last Step...", text_color="#00aaff", font=('calibri', 18))
        account_selection_message_1 = ctk.CTkLabel(self, text="-If you want to keep track of expenses across more than one account, select the account types from the list below.", text_color="#00aaff", font=('calibri', 15))
        account_selection_message_2 = ctk.CTkLabel(self, text="-You can also add one if it is not in the provided list (not implemented).", text_color="#00aaff", font=('calibri', 15))
        account_selection_message_3 = ctk.CTkLabel(self, text="-For each account selected, there will be an additional column in your budget for each month (So don't add too many!).", text_color="#00aaff", font=('calibri', 15))
        account_selection_message_4 = ctk.CTkLabel(self, text="-If you are new to budgeting \"All Accounts\" is recommended.", text_color="#00aaff", font=('calibri', 15))

        account_selection_checklist_frame = ctk.CTkScrollableFrame(self)
        account_selection_checklist_frame.grid_columnconfigure(0, weight=1)
        account_selection_checklist_frame.grid_rowconfigure(0, weight=1)
        
        self.account_selection_checkbox_list = []
        for index, account  in enumerate(self.default_account_name_list):
            if index == 0:
                account_selection_checkbox = ctk.CTkCheckBox(account_selection_checklist_frame, text=account, command=app_logic.not_checkable)
                account_selection_checkbox.select()
            else:
                account_selection_checkbox = ctk.CTkCheckBox(account_selection_checklist_frame, text=account, command=lambda: app_logic.user_selects_account())
            account_selection_checkbox.grid(row=0+index, column=0, sticky="wn", pady=5, padx=5)
            self.account_selection_checkbox_list.append(account_selection_checkbox)
        
        #layout
        account_selection_message_0.grid(row=0, column=0, columnspan=2, padx=80, pady=0, ipady=0, sticky="n")
        account_selection_message_1.grid(row=1, column=0, columnspan=2, padx=80, pady=0, ipady=0, sticky="nw")
        account_selection_message_2.grid(row=2, column=0, columnspan=2, padx=80, pady=0, ipady=0, sticky="nw")
        account_selection_message_3.grid(row=3, column=0, columnspan=2, padx=80, pady=0, ipady=0, sticky="nw")
        account_selection_message_4.grid(row=4, column=0, columnspan=2, padx=80, pady=0, ipady=0, sticky="nw")

        account_selection_checklist_frame.grid(row=5, column=0, columnspan=2, padx=80, sticky="nsew")

        app_logic.add_to_nav_map(system_name.value, self, self.page_func)
    
    #methods
    def draw_save_budget_window(self, app_logic: AppLogic):
        self.save_budget_window = SaveNameWindow(self, SaveObjectTypes.budget, app_logic)
        self.save_budget_window.focus()
        self.save_budget_window.grab_set()    

class SaveNameWindow(ctk.CTkToplevel):
    def __init__(self, master: Any, save_object_type: SaveObjectTypes, app_logic: AppLogic, save_object_title: str | None = None):
        super().__init__(master)

        #panel chars
        self.title("Save")
        self.geometry("400x240")
        self.minsize(400, 240)
        self.grid_columnconfigure((0), weight=1, uniform="a")
        self.grid_columnconfigure((1), weight=3, uniform="a")
        self.grid_columnconfigure((2), weight=3, uniform="a")
        self.grid_columnconfigure((3), weight=1, uniform="a")
        self.grid_rowconfigure((0,1,2), weight=1, uniform="a")

        #variables
        self.object_name_text = ctk.StringVar(value=save_object_title)

        #widgets
        self.save_object_label = ctk.CTkLabel(self, text="Save " + save_object_type.value, text_color="#00aaff", font=('calibri', 30))
        
        self.object_title_box = ctk.CTkEntry(self, textvariable=self.object_name_text)
        self.clear_titlebox = ctk.CTkButton(self, text="clear", fg_color='transparent', hover=False, text_color="#00aaff", font=('calibri', 12), command=lambda : app_logic.clear_title_box(self.object_title_box)) 
        
        self.cancel_button = ctk.CTkButton(self, text="Cancel", fg_color="#00aaff", font=('calibri', 22), command=self.destroy)
        self.save_button = ctk.CTkButton(self, text="Save", fg_color="#00aaff", font=('calibri', 22), command=lambda: app_logic.call_save_methods(save_object_type))

        #layout
        self.save_object_label.grid(row=0, column=1, columnspan=2, sticky="sew")

        self.object_title_box.grid(row=1, column=1, columnspan=2, sticky="ew")
        self.clear_titlebox.grid(row=1, column=3, sticky="e")

        self.cancel_button.grid(row=2, column=1, sticky="new", padx=5)
        self.save_button.grid(row=2, column=2, sticky="new", padx=5)

        app_logic.give_logic_temp_window_acess(save_window=self) #allow logic access to save window members once they exist 

        #events
        self.clear_titlebox.bind("<Enter>", lambda event: app_logic.on_hover_clear(event, self.clear_titlebox))
        self.clear_titlebox.bind("<Leave>", lambda event: app_logic.on_leave_clear(event, self.clear_titlebox))

        self.object_title_box.bind("<Return>", lambda event: app_logic.call_save_methods(save_object_type))

    #methods
    def draw_save_warning_window(self, app_logic, button_num: int, warning_title: WarningWindowText, warning_message: WarningWindowText):
        '''This method will generate a warning window when user tries to save an object that already exists, 
        \nand when confirmation of the save succeeds or fails
        \nButton_num can be a 1 (ok button only) or a 2 (cancel and confirm buttons)
        \nmessage and window title are passed using WarningWindowText Enum in Logic.py'''
        self.warning_window = WarningWindow(self, app_logic, button_num, warning_title, warning_message)
        self.warning_window.focus()
        self.warning_window.grab_set()

class WarningWindow(ctk.CTkToplevel):
    def __init__(self, master: Any, app_logic: AppLogic, button_num: int, warning_title: WarningWindowText, warning_message: WarningWindowText):
        super().__init__(master)

        #variables
        self.warning_title = warning_title
        self.app_logic = app_logic

        #count lines in warning message
        lines = warning_message.value.count("\n") + 1
        
        #get char num of longest line, for window width calculation
        longest_line = 0
        for line in warning_message.value.split("\n"):
            if len(line) > longest_line:
                longest_line = len(line) 

        #get button count, to set grid tuple
        columns = []
        count = 0
        for col in range(button_num):
            columns.append(count)
            count += 1

        #panel chars
        self.title(self.warning_title.value)
        width: int = int((100 * abs(longest_line / 28 - 1))) + 300
        height: int = 100 + (20 * lines)
        self.geometry(f'{width}x{height}')
        self.minsize(width, height)
        self.grid_rowconfigure((0,1), weight=1, uniform='a')
        self.grid_columnconfigure(columns, weight=1, uniform='a')

        #widgets and layout and events
        self.message = ctk.CTkLabel(self, text=warning_message.value, text_color="#00aaff", font=('calibri', 15))
        self.message.grid(row=0, column=0, columnspan=button_num, pady=10, padx=5, sticky="ews")
        if button_num == 1:
            self.ok_button = ctk.CTkButton(self, text="Ok", fg_color="#00aaff", font=('calibri', 18), command=lambda: app_logic.destroy_warning_and_save_windows(self))
            self.ok_button.grid(row=1, column=0, pady=10, padx=10, sticky="new")
            self.bind("<Return>", lambda event: self.destroy())
        elif button_num == 2 and self.warning_title.name != 'budget_save_confirmed_title': #cancel and confirm
            self.cancel_button = ctk.CTkButton(self, text="Cancel", fg_color="#00aaff", font=('calibri', 18), command=self.destroy)
            self.confirm_button = ctk.CTkButton(self, text="Confirm", fg_color="#00aaff", font=('calibri', 18), command=self.call_confirm_methods)
            self.cancel_button.grid(row=1, column=0, pady=10, padx=(10, 5), sticky="new")
            self.confirm_button.grid(row=1, column=1, pady=10, padx=(5, 10), sticky="new")
            self.bind("<Return>", lambda event: self.call_confirm_methods())
        elif button_num == 2 and self.warning_title.name == 'budget_save_confirmed_title': #return to main and go to manage
            self.return_to_main_button = ctk.CTkButton(self, text="Main Menu", fg_color="#00aaff", font=('calibri', 18), command=app_logic.return_to_mainmenu)
            self.goto_manage_button = ctk.CTkButton(self, text="Manage Budget", fg_color="#00aaff", font=('calibri', 18), command=app_logic.manage_new_budget)
            self.return_to_main_button.grid(row=1, column=0, pady=10, padx=(10, 5), sticky="new")
            self.goto_manage_button.grid(row=1, column=1, pady=10, padx=(5, 10), sticky="new")
            self.bind("<Return>", lambda event: app_logic.manage_new_budget())

    #methods
    def call_confirm_methods(self, event=None):
        if self.warning_title.name == 'template_exists_title':
            self.app_logic.save_budget_template()
        elif self.warning_title.name == 'budgetfile_exists_title':
            self.app_logic.build_budget_db_structure()

class ManageBudget(ctk.CTkFrame):
    def __init__(self, parent, system_name: SystemNames, app_logic: AppLogic, visual_theme: VisualThemes):
        super().__init__(master=parent)
        self.configure(corner_radius = 0)
        self.grid_columnconfigure((0,1), weight=1)
        self.grid_rowconfigure(0, weight=1) 
        self.grid_rowconfigure(1, weight=1)    
        self.grid_rowconfigure(2, weight=50) 

        #variables
        self.app_logic = app_logic
        self.cell_highlight_exists: bool = False
        self.page_func = app_logic.check_and_store_selected_budget
        self.drag_scrollbar_ytop: float = 1.0
        self.drag_scrollbar_ybottom: float = 1.0
        self.treeview_list: list[ttk.Treeview] = []
        self.scrollbar_list: list[ctk.CTkScrollbar] = []

        #widgets
        self.manage_budget_label = ctk.CTkLabel(self, text="Manage Budget: no budget selected", text_color="#00aaff", font=('calibri', 24))
        self.budgeted_surplus_shortfall_frame = ctk.CTkFrame(self, fg_color="transparent")
        self.budgeted_surplus_shortfall_label = ctk.CTkLabel(self.budgeted_surplus_shortfall_frame, text="Budgeted Surplus/Shortfall: ", text_color="#cccccc", font=("Calibri", 18))
        self.budgeted_surplus_shortfall_amount = ctk.CTkLabel(self.budgeted_surplus_shortfall_frame, text="$0.00", font=("Calibri", 18), fg_color="#272727")
        self.actual_surplus_shortfall_frame = ctk.CTkFrame(self, fg_color="transparent")
        self.actual_surplus_shortfall_label = ctk.CTkLabel(self.actual_surplus_shortfall_frame, text="Actual Surplus/Shortfall: ", text_color="#cccccc", font=("Calibri", 18))
        self.actual_surplus_shortfall_amount = ctk.CTkLabel(self.actual_surplus_shortfall_frame, text="$0.00", font=("Calibri", 18), fg_color="#272727")
        
        self.manage_budget_table_frame = ctk.CTkFrame(self)
        self.manage_budget_tabs = ctk.CTkTabview(self.manage_budget_table_frame, command=app_logic.set_active_treeview)
        self.tab_list = []
        for tab in self.app_logic.tab_title_list:
            new_tab = self.manage_budget_tabs.add(tab)
            self.tab_list.append(new_tab)      
        
        #layout
        self.manage_budget_label.grid(row=0, column=0, columnspan=2, sticky='new')

        self.budgeted_surplus_shortfall_frame.grid(row=1, column=0, sticky="ne", padx=10, pady=2)        
        self.budgeted_surplus_shortfall_amount.pack(side="right", padx=2, pady=2)
        self.budgeted_surplus_shortfall_label.pack(side="right", padx=2, pady=2)
        self.actual_surplus_shortfall_frame.grid(row=1, column=1, sticky="nw", padx=10, pady=2)
        self.actual_surplus_shortfall_label.pack(side="left", padx=2, pady=2)
        self.actual_surplus_shortfall_amount.pack(side="left", padx=2, pady=2)
        
        self.manage_budget_table_frame.grid(row=2, column=0, columnspan=2, padx=10, sticky='nsew')
        self.manage_budget_tabs.pack(expand=True, fill='both', pady=5, padx=5)

        app_logic.add_to_nav_map(system_name.value, self, self.page_func)
        visual_theme.apply_style_table(self)
        
    #methods and events
    def create_management_treeviews(self):
        for tab in self.tab_list:
            self.budget_table = ttk.Treeview(tab, show='headings', style="Treeview")         
            self.budget_table_scrollbar = ctk.CTkScrollbar(tab, command=self.drag_scrollbar)
            self.treeview_list.append(self.budget_table) 
            self.scrollbar_list.append(self.budget_table_scrollbar)         
            self.budget_table_scrollbar.pack(side='right', fill='y')
            self.budget_table.pack(side='left', expand=True, fill='both', pady=5, padx=5)          
            self.budget_table.configure(yscrollcommand=self.budget_table_scrollbar.set)   
            self.set_bindings(0) #NOTE: if default tab is ever set by date or last user interaction, this 0 will need to be set by that functionality

    def destroy_management_treeviews(self):
        for treeview, scrollbar in zip(self.treeview_list, self.scrollbar_list):
            treeview.destroy()
            scrollbar.destroy()
        self.treeview_list = []
        self.scrollbar_list = []

    def set_bindings(self, active_tab: int):
        self.treeview_list[active_tab].bind("<Button-1>", lambda event: self.app_logic.budget_manager_single_click(event, self.treeview_list[active_tab]))
        self.treeview_list[active_tab].bind("<MouseWheel>", lambda event: self.treeview_scroll(event)) #also bind to summary columns?

    def draw_cell_highlight(self, hierarchy_name: ttk.Treeview, proper_cell: bool):
        if proper_cell:
            self.cell_x_pos, self.cell_y_pos, self.cell_width, self.cell_height = self.app_logic.set_selected_cell_location(hierarchy_name)
            self.cell_highlight = ctk.CTkFrame(hierarchy_name, width=self.cell_width, height=self.cell_height, corner_radius=0, fg_color="#AAAAAA")
            self.cell_highlight.place(x=self.cell_x_pos, y=self.cell_y_pos)
            self.cell_highlight_exists = True
            self.cell_highlight.bind("<Double-1>", lambda event: self.app_logic.invoke_manage_budget_buttons(event))
            self.cell_highlight.bind("<Button-1>", lambda event: self.app_logic.invoke_manage_budget_buttons(event))
            self.after(50, self.set_cell_highlight_focus)
            self.after(500, self.unbind_single_click)
            cell_highlight_id = self.cell_highlight.winfo_id()
            pywinstyles.set_opacity(cell_highlight_id, value=0.1)
        else: pass

    def drag_scrollbar(self, *args):
        self.treeview_list[self.app_logic.current_tab_num].yview(*args)
        if self.cell_highlight_exists:
            try:
                self.cell_x_pos, self.cell_y_pos, self.cell_width, self.cell_height = self.app_logic.set_selected_cell_location(self.treeview_list[self.app_logic.current_tab_num])
                self.cell_highlight.place(x=self.cell_x_pos, y=self.cell_y_pos)
            except IndexError:
                self.cell_highlight.place_forget() #selected cell out of view, unmap cell highlight
                
    def treeview_scroll(self, event): 
        '''reads current position of the top and bottom of the scrollbar, 
        \nthen if not at the top/bottom, adjusts the cell highlight by the cell height 
        \n(this is how much the treeview scrolls per mousewheel tick)'''       
        y_top, y_bottom = self.treeview_list[self.app_logic.current_tab_num].yview()
        if self.cell_highlight_exists:       
            if event.delta < 0 and y_bottom < 1: #scrolling down and not at bottom, adjust y up 
                self.cell_y_pos -= self.cell_height   
                self.cell_highlight.place(x=self.cell_x_pos, y=self.cell_y_pos)
            elif event.delta > 0 and y_top > 0: #scrolling up, adjust y down
                self.cell_y_pos += self.cell_height
                self.cell_highlight.place(x=self.cell_x_pos, y=self.cell_y_pos)
        else: pass

    def unbind_single_click(self):
        try:
            self.cell_highlight.unbind("<Button-1>")
        except Exception: #if user clicks a different cell before 500ms timer, the widget was destroyed causing TclError
            pass 

    def set_cell_highlight_focus(self):
        self.cell_highlight.focus_set()  

    def draw_transaction_list_window(self):
        self.transaction_list_window = TransactionListWindow(self, self.app_logic)
        self.transaction_list_window.focus()
        self.transaction_list_window.grab_set()
    
    def draw_transaction_editor_window(self, add_new_button: bool, called_by_manager: bool=False):
        self.transaction_editor_window = TransactionEditorWindow(self, self.app_logic, add_new_button, called_by_manager)
        self.transaction_editor_window.focus()
        self.transaction_editor_window.grab_set()

class TransactionListWindow(ctk.CTkToplevel):
    def __init__(self, master: Any, app_logic: AppLogic, ):
        super().__init__(master)

        #window chars
        self.title("Transactions List")
        self.geometry("600x550")
        self.minsize(600, 550)
        self.grid_columnconfigure((0,1,2,3,4), weight=1, uniform='a')
        self.grid_rowconfigure((0,1,2,3), weight=1, uniform='a')
        self.grid_rowconfigure(4, weight=50)
        self.grid_rowconfigure(5, weight=10)

        #variables
        self.app_logic = app_logic

        #widgets
        self.transactions_for = ctk.CTkLabel(self, text="Transactions for: ", text_color="#00aaff", font=('calibri', 24))
        self.transactions_for_info = ctk.CTkLabel(self, text="Annual/Month, Account, Income/Expenses", text_color="#00aaff", font=('calibri', 24))
        self.transactions_for_info_category = ctk.CTkLabel(self, text="Category", text_color="#00aaff", font=('calibri', 24))
        self.transactions_for_info_subcategory = ctk.CTkLabel(self, text="Sub-Category", text_color="#00aaff", font=('calibri', 24))

        self.cell_transaction_list_frame = ctk.CTkScrollableFrame(self)
        self.cell_transaction_list_frame.grid_columnconfigure(0, weight=1)
        self.cell_transaction_list_frame.grid_rowconfigure(0, weight=1)

        self.transaction_list_cancel_button = ctk.CTkButton(self, text="Cancel", fg_color="#00aaff", font=('calibri', 24), command=self.destroy)
        self.transaction_list_add_new_button = ctk.CTkButton(self, text="Add New", fg_color="#00aaff", font=('calibri', 24), command=lambda add_new_button=True: self.draw_transaction_editor_window(add_new_button))
        self.transaction_list_edit_button = ctk.CTkButton(self, text="Edit", fg_color="#00aaff", font=('calibri', 24), state="disabled", command=lambda: app_logic.edit_transactions())
        self.transaction_list_delete_button = ctk.CTkButton(self, text="Delete", fg_color="#00aaff", font=('calibri', 24), state="disabled", command=lambda: app_logic.delete_transactions_in_list())
        self.transaction_list_confirm_button = ctk.CTkButton(self, text="Confirm", fg_color="#00aaff", font=('calibri', 24), command=lambda: app_logic.confirm_transaction_list())

        #layout
        self.transactions_for.grid(row=0, column=0, columnspan=5, sticky="n")
        self.transactions_for_info.grid(row=1, column=0, columnspan=5, sticky="n")
        self.transactions_for_info_category.grid(row=2, column=0, columnspan=5, sticky="n")
        self.transactions_for_info_subcategory.grid(row=3, column=0, columnspan=5, sticky="n")

        self.cell_transaction_list_frame.grid(row=4, column=0, columnspan=5, sticky="nsew", padx=10, pady=(5,0))

        self.transaction_list_cancel_button.grid(row=5, column=0, sticky="ew", padx=(10,5), pady=(0,5))
        self.transaction_list_add_new_button.grid(row=5, column=1, sticky="ew", padx=5, pady=(0,5))
        self.transaction_list_edit_button.grid(row=5, column=2, sticky="ew", padx=5, pady=(0,5))
        self.transaction_list_delete_button.grid(row=5, column=3, sticky="ew", padx=5, pady=(0,5))
        self.transaction_list_confirm_button.grid(row=5, column=4, sticky="ew", padx=(5,10), pady=(0,5))

        app_logic.give_logic_temp_window_acess(transaction_list_window=self)

    #methods
    def create_transaction_list(self, cell_transactions: list):
        self.transaction_checkbox_list: list = []
        self.checkbox_statuses: list = []
        for index, transaction in enumerate(cell_transactions):
            transaction_checkbox = ctk.CTkCheckBox(self.cell_transaction_list_frame, text='${:,.2f}'.format(transaction[-1]), command=lambda: self.app_logic.user_selects_transaction())
            self.transaction_checkbox_list.append(transaction_checkbox)
            self.checkbox_statuses.append(0)
            transaction_checkbox.grid(row=0+index, column=0, sticky="wn", pady=5, padx=5)

    def add_transaction_to_list(self, transaction_amount: float):
        transaction_amount_str: str = '${:,.2f}'.format(transaction_amount)
        new_transaction_checkbox = ctk.CTkCheckBox(self.cell_transaction_list_frame, text=transaction_amount_str + TrasactionStatuses.new.value, command=lambda: self.app_logic.user_selects_transaction())
        self.transaction_checkbox_list.append(new_transaction_checkbox)
        new_transaction_checkbox.grid(row=len(self.transaction_checkbox_list), column=0, sticky="wn", pady=5, padx=5)
        self.checkbox_statuses.append(0)
    
    def draw_transaction_editor_window(self, add_new_button: bool, called_by_manager: bool=False):
        self.transaction_editor_window = TransactionEditorWindow(self, self.app_logic, add_new_button, called_by_manager)
        self.transaction_editor_window.focus()
        self.transaction_editor_window.grab_set()

class TransactionEditorWindow(ctk.CTkToplevel):
    def __init__(self, master: Any, app_logic: AppLogic, add_new: bool, called_by_manager: bool):
        super().__init__(master)
        
        #window chars
        self.title("Edit Transaction")
        self.geometry("500x550")
        self.minsize(500, 550)
        self.grid_columnconfigure((0,1), weight=1, uniform='a')
        self.grid_rowconfigure((0), weight=1, uniform='a')
        self.grid_rowconfigure(1, weight=50)
        self.grid_rowconfigure(2, weight=10)

        # #variables
        self.app_logic = app_logic
        self.amount_entry_focused = False
        
        self.dropdown_tab_name = ctk.StringVar(value=self.app_logic.selected_cell_info_list[0])
        self.dropdown_account_name = ctk.StringVar(value=self.app_logic.selected_cell_info_list[1])
        self.dropdown_incexp = ctk.StringVar(value=self.app_logic.selected_cell_info_list[2])
        self.dropdown_category_name = ctk.StringVar(value=self.app_logic.selected_cell_info_list[3])
        self.dropdown_subcat_name = ctk.StringVar(value=self.app_logic.selected_cell_info_list[4])
        self.entrybox_amount = ctk.StringVar(value="")

        #widgets
        self.transaction_editor_title = ctk.CTkLabel(self, text="Transaction Editor", text_color="#00aaff", font=('calibri', 24))
        self.transaction_form_frame = ctk.CTkFrame(self)
        self.annual_month_label = ctk.CTkLabel(self.transaction_form_frame, text="Annual/Month", text_color="#00aaff", font=('calibri', 24))
        self.annual_month_dropdown = ctk.CTkComboBox(self.transaction_form_frame, width=250, values=self.app_logic.tab_title_list[:-1], variable=self.dropdown_tab_name, state='readonly', command=lambda annual=self.dropdown_tab_name: self.app_logic.set_dropdowns_to_annual_or_month(annual))
        self.account_label = ctk.CTkLabel(self.transaction_form_frame, text="Account", text_color="#00aaff", font=('calibri', 24))
        self.account_dropdown = ctk.CTkComboBox(self.transaction_form_frame, width=250, values=self.app_logic.budget_accounts_name_list, variable=self.dropdown_account_name, state='readonly')
        self.income_expense_label = ctk.CTkLabel(self.transaction_form_frame, text="Income or Expense", text_color="#00aaff", font=('calibri', 24))
        self.income_expense_dropdown = ctk.CTkComboBox(self.transaction_form_frame, width=250, values=self.app_logic.income_expense_str_list, variable=self.dropdown_incexp, state='readonly', command=lambda incexp=self.dropdown_incexp: self.app_logic.set_dropdown_categories(incexp, set_default=True))
        self.category_label = ctk.CTkLabel(self.transaction_form_frame, text="Category", text_color="#00aaff", font=('calibri', 24))
        self.category_dropdown = ctk.CTkComboBox(self.transaction_form_frame, width=250, values=[], variable=self.dropdown_category_name, state='readonly', command=lambda category=self.dropdown_category_name: self.app_logic.set_dropdown_subcategories(category, set_default=True))
        self.subcategory_label = ctk.CTkLabel(self.transaction_form_frame, text="Sub-category", text_color="#00aaff", font=('calibri', 24))
        self.subcategory_dropdown = ctk.CTkComboBox(self.transaction_form_frame, width=250, values=[], variable=self.dropdown_subcat_name, state='readonly')
        self.amount_label = ctk.CTkLabel(self.transaction_form_frame, text="Amount", text_color="#00aaff", font=('calibri', 24))
        self.amount_entry = ctk.CTkEntry(self.transaction_form_frame, width=250, textvariable=self.entrybox_amount)

        self.transaction_editor_cancel_button = ctk.CTkButton(self, text="Cancel", fg_color="#00aaff", font=('calibri', 24), command=lambda: self.app_logic.close_editor_window(add_new, True))
        self.transaction_editor_confirm_button = ctk.CTkButton(self, text="Confirm", fg_color="#00aaff", font=('calibri', 24), command=lambda: app_logic.confirm_transaction_editor(called_by_manager, add_new))

        #layout
        self.transaction_editor_title.grid(row=0, column=0, columnspan=2, sticky="n")

        self.transaction_form_frame.grid(row=1, column=0, columnspan=2, sticky="nsew", padx=10, pady=(5,0))
        self.annual_month_label.pack(pady=5)
        self.annual_month_dropdown.pack()
        self.account_label.pack(pady=5)
        self.account_dropdown.pack()
        self.income_expense_label.pack(pady=5)
        self.income_expense_dropdown.pack()
        self.category_label.pack(pady=5)
        self.category_dropdown.pack()
        self.subcategory_label.pack(pady=5)
        self.subcategory_dropdown.pack()
        self.amount_label.pack(pady=5)
        self.amount_entry.pack()

        self.transaction_editor_cancel_button.grid(row=2, column=0, sticky="w", padx=10, pady=(0,5))
        self.transaction_editor_confirm_button.grid(row=2, column=1, sticky="e", padx=10, pady=(0,5))

        if add_new: #if "add new" button pressed, dropdowns should be disabled
            self.annual_month_dropdown.configure(state="disabled")
            self.account_dropdown.configure(state="disabled")
            self.income_expense_dropdown.configure(state="disabled")
            self.category_dropdown.configure(state="disabled")
            self.subcategory_dropdown.configure(state="disabled")
        if not add_new:
            self.entrybox_amount.set(app_logic.cell_transactions_from_db[app_logic.current_transaction_to_edit][-1])
        
        app_logic.give_logic_temp_window_acess(transaction_editor_window=self)
        app_logic.set_dropdown_categories(self.dropdown_incexp.get(), False)

        #events
        self.amount_entry.bind("<FocusIn>", app_logic.set_bindings_to_amount_entry)
        
        self.annual_month_dropdown.bind("<FocusIn>", app_logic.keep_focus_in_entry)
        self.account_dropdown.bind("<FocusIn>", app_logic.keep_focus_in_entry)
        self.income_expense_dropdown.bind("<FocusIn>", app_logic.keep_focus_in_entry)
        self.category_dropdown.bind("<FocusIn>", app_logic.keep_focus_in_entry)
        self.subcategory_dropdown.bind("<FocusIn>", app_logic.keep_focus_in_entry)
        
        self.after(100, app_logic.set_focus_to_entry)

    def set_returnkey_binding(self): #links enter key to confirm button
        self.amount_entry.bind("<Return>", self.app_logic.returnkey_pressed_in_amount_entry)



    